services:
  - type: web
    name: ai-lawyer
    env: python
    buildCommand: ""
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000
    envVars:
      - key: GEMINI_API_KEY
        value: ${GEMINI_API_KEY}
    rootDir: backend
